### ISSUE TITLE
using dynamic country input

### ISSUE THREAD

**Issue by MincePie** [evgenygarl/flag-icons-rails#19]
Hello, 

What do you mean by:

> Do not add gem to assets section if you want to use flag_icon rails helper.

Does that mean not to add:

`@import "flag-icon";
`
to application.scss?

Also, how do I add dynamic content to the helper? I have an address model which has a country attribute. It stores the "BY".

I'm trying to pass that to the helper:
```

<%= flag_icon(Address.last.country) %>

        <%= flag_icon(Address.last.country.to_sym) %>
```

Neither of those attempts work. Can I use flags dynamically?

**Comment by eddibravo** [comment]
@MincePie use `downcase`
`<%= flag_icon(Address.last.country.downcase.to_sym) %>`

**Comment by eugenegarl** [comment]
@MincePie  Sorry for delay with answer 😞 

> Do not add gem to assets section if you want to use flag_icon rails helper.  

means do not adding this gem into `group :assets` into your Gemfile. By the way, this group is not supported beginning from Rails 4 😄 
`@import "flag-icon";` is required, because all styles contain all rules to display flags in SVG.

As for using `flag_icon` helper method, it expects downcased [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code as a first argument. Converting to symbol is not required, because this argument will be casted to string whatever.

Hope, this answer will be helpful 😃
